# Generated by Django 5.0.4 on 2024-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_productinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='qty_in_metres',
            field=models.FloatField(default=None, null=True),
        ),
    ]
