# Generated by Django 5.0.4 on 2024-05-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_cost_productinventory_cost_sqmtr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinventory',
            old_name='cost_sqmtr',
            new_name='cost_sqft',
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='qty_sqmtr',
            new_name='qty_sqft',
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='selling_price_sqmtr',
            new_name='selling_price_sqft',
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='total_amount_sqmtr',
            new_name='total_amount_sqft',
        ),
    ]
