# Generated by Django 5.0.4 on 2024-05-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_salescustomerdata_purchase_qty_in_sqft'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescustomerdata',
            name='sale_price_sqft',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salescustomerdata',
            name='total_sale_amount',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
