# Generated by Django 5.0.4 on 2024-05-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_salescustomerdata_sale_price_sqft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salescustomerdata',
            old_name='purchase_qty_in_sqft',
            new_name='qty_in_sqft',
        ),
        migrations.RenameField(
            model_name='salescustomerdata',
            old_name='purchase_date',
            new_name='sales_date',
        ),
        migrations.RenameField(
            model_name='salescustomerdata',
            old_name='purchase_product',
            new_name='sales_product',
        ),
    ]
