# Generated by Django 5.0.4 on 2024-05-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_productinventory_first_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='first_purchase_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='last_purchase_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
