# Generated by Django 5.0.4 on 2024-07-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_customers_order_from_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='website_orderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.FloatField()),
                ('qty', models.FloatField()),
                ('gross_amount', models.FloatField()),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.customers_order_from_website')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.productinventory')),
            ],
        ),
    ]
