# Generated by Django 5.0.4 on 2024-07-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_website_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_orderitems',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
