# Generated by Django 5.0.4 on 2024-07-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_website_orderitems_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_orderitems',
            name='payment_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
