# Generated by Django 5.0.4 on 2024-07-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_website_orderitems_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_orderitems',
            name='order_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
