# Generated by Django 5.0.4 on 2024-07-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_website_orderitems_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website_orderitems',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='website_orderitems',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='website_orderitems',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='customers_order_from_website',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customers_order_from_website',
            name='order_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers_order_from_website',
            name='payment_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
