# Generated by Django 5.0.4 on 2024-07-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_customers_order_from_website_is_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queryform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=14)),
                ('message', models.TextField()),
            ],
        ),
    ]
