# Generated by Django 5.0.4 on 2024-07-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_queryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.FileField(blank=True, default='profiles/default-profile.png', null=True, upload_to='profiles'),
        ),
    ]
