# Generated by Django 5.0.4 on 2024-07-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_queryform_query_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers_order_from_website',
            name='user_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
