# Generated by Django 5.0.4 on 2024-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_customers_order_from_website_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescustomerdata',
            name='discount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
